import type { NextPage } from "next";
import Head from "next/head";
import StressForm from "../components/StressForm";

const Home: NextPage = () => {
  return (
    <div className="bg-neutral-900 min-h-screen text-neutral-200 mx-auto flex justify-center items-center">
      <Head>
        <title>Stress Tracking</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <StressForm />
      </main>
    </div>
  );
};

export default Home;
